### ISSUE TITLE
A few files missing

### ISSUE THREAD

**Issue by jesperordrup** [pikachuPokemon/Selfie-Fun#1]
These are referenced from app.scss but not to be found:

.meteor/local/build/programs/server/assets/packages/meteoric_ionic-sass/ionic
.meteor/local/build/programs/server/assets/packages/meteoric_ionicons-sass/_ionicons

Cool project :)

**Comment by akshaykmr** [comment]
I ran into this problem when I once reset the whole project. I got it to work by removing and adding meteoric and sass packages but it may not work.

For now, I've attached the files from the project's build directory on my system. Just replace the stylesheets folder with this one.

https://drive.google.com/file/d/0BwOJHtE5_WFBZWVPLW56Qi1tUGc/view?usp=sharing

**Comment by jesperordrup** [comment]
:+1:

**Comment by akshaykmr** [comment]
I'll leave the issue open till packages gets fixed in case anybody else has the same problem.
